# This is a basic workflow to help you get started with Actions
name: Merge branch with labeled
on:
  push
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge by labeled
        uses: devmasx/merge-branch@v1.3.1
        with:
          label_name: 'merged in dev'
          target_branch: 'dev'
          github_token: ${{ github.token }}
